#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TcpPoc.Droid.Resource", IsApplication=true)]

namespace TcpPoc.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7F010000
			public const int planets_array = 2130771968;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int button_shape = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int EditTextStyle = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int logo_miratorg = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int Button_Set_0 = 2130903040;
			
			// aapt resource value: 0x7F030002
			public const int connectButton = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int connectionStatus = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int imageView1 = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int ipText = 2130903045;
			
			// aapt resource value: 0x7F030001
			public const int LinearLayot_Weight = 2130903041;
			
			// aapt resource value: 0x7F030006
			public const int portText = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int progressBar = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int textView_KG = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int textView_Label_Data = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int textView_Stable = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int textView_Weight = 2130903051;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int Main = 2130968576;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F050000
			public const int ApplicationName = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int Hello = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int planet_prompt = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
